version: '3'

networks:
  indy-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IDC_API_SUBNET-172.16.0.0/24}

services:
  pool:
    image: idchain/test-pool:latest
    ports:
      - ${IDC_POOL_PORTS-9701-9708}:${IDC_POOL_PORTS-9701-9708}
      - 8001:8001
    environment:
      - IDC_POOL_NAME=${IDC_POOL_NAME-testPool}
      - IDC_POOL_IP=${IDC_POOL_IP-172.16.0.200}
      - IDC_PORT_START=${IDC_PORT_START-9700}
    networks:
      indy-network:
        ipv4_address: ${IDC_POOL_IP-172.16.0.200}

  legacy-government:
    image: idchain/legacy-goverment:latest
    container_name: gov-legacy
    ports:
      - ${GOV_PORT-8090}:${GOV_PORT-8090}
    environment:
      - IDC_API_HOST=${IDC_API_HOST-172.16.0.100}
      - IDC_API_PORT=${IDC_API_PORT-8000}
      - GOV_HOST=${GOV_HOST-172.16.0.101}
      - GOV_PORT=${GOV_PORT-8090}
      - GOV_DID=${GOV_DID-Th7MpTaRZVRYnPiabds81Y}
      - GOV_SEED=${GOV_SEED-0000000000000000000000Government}
      - GOV_USER=${GOV_USER-government}
      - GOV_PASSWORD=${GOV_PASSWORD-dummy}
      - GOV_WALLET=${GOV_WALLET-governmentWallet}
      - GOV_WALLET_KEY=${GOV_WALLET_KEY-dummy}
      - GOV_NAME
      - GOV_DESCRIPTION
      - GOV_LOGO_URL
      - GOV_START_UP_INTERVAL=${GOV_START_UP_INTERVAL-5000}
    networks:
      indy-network:
        ipv4_address: ${GOV_HOST-172.16.0.101}

  mongodb:
    image: mongo:4
    command: --smallfiles
    container_name: gov-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${IDC_API_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${IDC_API_DB_PASSWORD}
    networks:
      - indy-network

  schema:
    image: idchain/schema-extensions:1.0
    container_name: gov-schema
    environment:
      - IDC_SCHEMA_IP=${IDC_SCHEMA_IP-172.16.0.150}
      - IDC_SCHEMA_PORT=${IDC_SCHEMA_PORT-9000}
    networks:
      indy-network:
        ipv4_address: ${IDC_SCHEMA_IP-172.16.0.150}

  admin-ui:
    image: idchain/admin-ui:latest
    container_name: gov-admin
    ports:
      - 8080:${NGINX_PORT-80}
    environment:
      - NGINX_HOST=${NGINX_HOST-172.16.0.105}
      - NGINX_PORT=${NGINX_PORT-80}
      - IDC_API_DOMAIN_PROTOCOL=${IDC_API_DOMAIN_PROTOCOL-http}
      - IDC_API_DOMAIN_HOST=${IDC_API_DOMAIN_HOST-172.16.0.100}
      - IDC_API_DOMAIN_PORT=${IDC_API_DOMAIN_PORT-8000}
    depends_on:
      - api
    networks:
      indy-network:
        ipv4_address: ${NGINX_HOST-172.16.0.105}

  api:
    image: idchain/iea-api:latest
    container_name: gov-api
    environment:
      - RUST_LOG=${RUST_LOG-debug}
      - IDC_API_LOG_LEVEL=${IDC_API_LOG_LEVEL-debug}
      - IDC_API_HOST=${IDC_API_HOST-172.16.0.100}
      - IDC_API_PORT=${IDC_API_PORT-8000}
      - IDC_API_DOMAIN_PROTOCOL=${IDC_API_DOMAIN_PROTOCOL-http}
      - IDC_API_DOMAIN_HOST=${IDC_API_DOMAIN_HOST-172.16.0.100}
      - IDC_API_DOMAIN_PORT=${IDC_API_DOMAIN_PORT-8000}
      - IDC_API_NYM_ALWAYS=${IDC_API_NYM_ALWAYS-false}
      - IDC_API_JWT_SECRET=${IDC_API_JWT_SECRET-changeme}
      - IDC_API_DB_HOST=${IDC_API_DB_HOST-mongodb}
      - IDC_API_DB_PORT=${IDC_API_DB_PORT-27017}
      - IDC_API_DB_USER
      - IDC_API_DB_PASSWORD
      - IDC_API_SALTROUNDS=${IDC_API_SALTROUNDS-10}
      - IDC_API_GENESIS_TXN=${IDC_API_GENESIS_TXN-./pool_transactions_genesis}
      - IDC_POOL_IP=${IDC_POOL_IP-172.16.0.200}
      - IDC_POOL_NAME=${IDC_POOL_NAME-testPool}
      - IDC_POOL_INFO_PORT=${IDC_POOL_INFO_PORT-8001}
      - IDC_SCHEMA_IP=${IDC_SCHEMA_IP-172.16.0.150}
      - IDC_SCHEMA_PORT=${IDC_SCHEMA_PORT-9000}
    ports:
      - ${IDC_API_PORT-8000}:${IDC_API_PORT-8000}
    depends_on:
      - mongodb
      - schema
      - pool
    networks:
      indy-network:
        ipv4_address: ${IDC_API_HOST-172.16.0.100}
